### ISSUE TITLE
Decoders?

### ISSUE THREAD

**Issue by mikeplus64** [nikita-volkov/hasql-implicits#7]
Would be nice to have some implicit decoders as well.

Something like

```
class DefaultValueDecoder a where
  defaultValue :: Value a
```

Rows, if they are to be added, are probably calling for something like `product-profunctors` where the idea is to promote a constructor [or anything like `sqlType -> hsType`] to a parser for that constructor. Or using `Generic` is quite doable though inevitably annoying when a new GHC version breaks it. Or rolling your own minimal version of profunctors isn't so bad:

```
class DefaultRowDecoder a where
  defaultRow :: D.Row a

-- Maybe ==> nullable
-- Non-maybe ==> nonNullable

liftDefaultRow :: (LiftDefaultRowDecoder a f) => f -> D.Row a
liftDefaultRow f = defaultRowP (pure f)

class LiftDefaultRowDecoder a f where
  defaultRowP :: D.Row f -> D.Row a -- dunno what's a good name here

instance (DefaultRowDecoder x, LiftDefaultRowDecoder r' r) => LiftDefaultRowDecoder r' (x -> r) where
  defaultRowP r = defaultRowP (r <*> defaultRow)

instance LiftDefaultRowDecoder r r where
  defaultRowP r = r




data MyNiceRowResult = MyNiceRowResult { a, b, c, d :: Text }

someRowDecoder :: Row MyNiceRowResult -- Requires annotation or type application to solve instances
someRowDecoder = liftDefaultRow MyNiceRowResult

```

**Comment by nikita-volkov** [comment]
This all looks interesting and may be a good basis for your own library. You clearly have a vision there. If your lib will become the norm I'll deprecate this one and replace it with yours in hasql-dynamic-statements.

**Comment by nikita-volkov** [comment]
Also please beware that there also exists at least [one other library](https://hackage.haskell.org/package/hasql-class-0.0.0.1/docs/Hasql-Class.html) in this category. There may be more.

**Comment by nikita-volkov** [comment]
There's also [a lib for generics](https://hackage.haskell.org/package/hasql-generic).

**Comment by mikeplus64** [comment]
Fair enough. I hadn't seen those other two libraries. The only sad part is thinking of a name zingier than "hasql-implicits" :). I guess "hasql-defaults" is OK.

**Comment by mikeplus64** [comment]
> This all looks interesting and may be a good basis for your own library. You clearly have a vision there. If your lib will become the norm I'll deprecate this one and replace it with yours in hasql-dynamic-statements.

Long time no update: I've uploaded https://hackage.haskell.org/package/hasql-auto-0.1.0.0/candidate just now, finally spurred on by wanting to get this out of an existing project and into its own thing :). The original `Hasql.Implicits.Encoders` is almost identical in this, but now with two instances for encoding a value via `jsonb` or `json`, plus defining an entire `Params` via `generics-sop` (similar to hasql-generic). If you have time: how does this look?

**Comment by nikita-volkov** [comment]
Good. Thanks!

Please take into account that now there's also https://hackage-content.haskell.org/package/hasql-mapping-0.1.0.1/docs/Hasql-Mapping-IsScalar.html. The intent there is to only automate the codecs for individual scalar values, intending the rest to be composed by other means (usually manually or via solutions like yours). I'm heavily using the "hasql-mapping" lib in https://pgenie.io.

**Comment by mikeplus64** [comment]
> Good. Thanks!
> 
> Please take into account that now there's also https://hackage-content.haskell.org/package/hasql-mapping-0.1.0.1/docs/Hasql-Mapping-IsScalar.html. The intent there is to only automate the codecs for individual scalar values, intending the rest to be composed by other means (usually manually or via solutions like yours). I'm heavily using the "hasql-mapping" lib in https://pgenie.io.

Cheers and nice, I was wondering if pGenie had its own similar thing under the hood as well. Looks like I missed a few instances like `inet`, `uuid`, `macaddr`. Having an `IsScalar` like class is a nice approach, I can cut down on needing 378 individual instances in `Hasql.Auto.Encoders`... I think it should be fine wrt overlapping instances because nothing that satisfies `IsScalar` would be a type that would also have a conflicting `DefaultParamEncoder` instance.
